[urls]
products_reordering = "https://drive.google.com/file/d/1j3N5DefIVRuZCiLroMIe0Xs1Y2f7btdQ/view?usp=share_link"
products_reordering_percentages = "https://drive.google.com/file/d/1BQol0G16bFsyGp-2pgHLbeAyrcL4tFLc/view?usp=share_link"
days_bins = "https://drive.google.com/file/d/1_QKQGf25GS6-BWpT42qpWOrEg8uf-FSx/view?usp=share_link"
days_total_counts = "https://drive.google.com/file/d/1GgYTpYXx6pD2W9u8X5XG7RXZ7pIlZ6UW/view?usp=share_link"
days_reordered_counts = "https://drive.google.com/file/d/18MPkScBhEbJBzhzkLt-q-ZyWwq9eka3_/view?usp=share_link"
cart_bins = "https://drive.google.com/file/d/1Fymi1njrhJISFhGKIgB1hNmMknp_x-yI/view?usp=share_link"
cart_total_counts = "https://drive.google.com/file/d/1ifIrlhnkTR_ELnwQspahxydURaGBOfxc/view?usp=share_link"
cart_reordered_counts = "https://drive.google.com/file/d/1pbGRTjbkwct_P_CcSvQ412vB9ArWunBR/view?usp=share_link"
frequency_ratings = "https://drive.google.com/file/d/1VM0pYXtsf0JDhrBx6VAGucOMydcmi5Mw/view?usp=share_link"
days_ratings = "https://drive.google.com/file/d/1g2SCF7waIj5xuwCYoUV9iOf6PV5muD58/view?usp=share_link"
cart_ratings = "https://drive.google.com/file/d/1jZG3cLPOjKi6Coc3GgO4VBeukoCwgbO0/view?usp=share_link"
total_ratings = "https://drive.google.com/file/d/1Sng4F4aMM3q9r_LVSZOr5KlsC8pMYtEh/view?usp=share_link"
frequency_map_10 = "https://drive.google.com/file/d/1wXs48DEq862wbSLBfqFU935cxIcHHuu-/view?usp=share_link"
days_map10 = "https://drive.google.com/file/d/1bW6WH7ihyvD814TQNkhE2HnvOeKCYwht/view?usp=share_link"
cart_map10 = "https://drive.google.com/file/d/1OAaG9Lx8AkZynpgDdJr9z29VjvZjsR_W/view?usp=share_link"
total_map10 = "https://drive.google.com/file/d/15wXyDer9En08zSms6xJxw7RQ_GkHs2hB/view?usp=share_link"
map10_days = "https://drive.google.com/file/d/1q4F4G-vRNXIG3YqAXELrPgI0_v4hTCRt/view?usp=share_link"
map10_cart = "https://drive.google.com/file/d/1nSyg6XBJ5_RevCEhQB32gOEaXwHRf1SK/view?usp=share_link"
map10_total = "https://drive.google.com/file/d/1_LSkW-MDHegHmqvJn4s63GdKpbQE6VVR/view?usp=share_link"
map10_days_pred = "https://drive.google.com/file/d/1f3A5oxQBTEMsqNXYCRBzBeKasnkLC1rX/view?usp=share_link"
map10_cart_pred = "https://drive.google.com/file/d/1ADI-QjzytZP84gmXV4uTKjgpzH59gEVt/view?usp=share_link"
map10_total_pred = "https://drive.google.com/file/d/15ndBysmccz-S-iVkZ0xzdDdT6ro77X3-/view?usp=share_link"
days_rate = "https://drive.google.com/file/d/1PGlwRZQrDGxxaIxk4Jb9nFR6cq3VKuII/view?usp=share_link"
cart_rate = "https://drive.google.com/file/d/1Du-D1MGkMGcQhGFDNsspChkaqHoTjUx8/view?usp=share_link"
total_rate = "https://drive.google.com/file/d/1vGWNvruJr4Clwcsz0pSk3tIlRfrfjPSM/view?usp=share_link"
missed_last_products = "https://drive.google.com/file/d/1AnEvz_4u2YU9Llhbx0V7vethNgfKZ9Yn/view?usp=share_link"
test_results = "https://drive.google.com/file/d/1GqV6rKKfNm3cAl6QBCTsGFBYh5ep4q2v/view?usp=share_link"