[urls]
products_reordering = "https://drive.google.com/file/d/1j3N5DefIVRuZCiLroMIe0Xs1Y2f7btdQ/view?usp=share_link"
products_reordering_percentages = "https://drive.google.com/file/d/1BQol0G16bFsyGp-2pgHLbeAyrcL4tFLc/view?usp=share_link"
days_bins = "https://drive.google.com/file/d/1_QKQGf25GS6-BWpT42qpWOrEg8uf-FSx/view?usp=share_link"
days_total_counts = "https://drive.google.com/file/d/1GgYTpYXx6pD2W9u8X5XG7RXZ7pIlZ6UW/view?usp=share_link"
days_reordered_counts = "https://drive.google.com/file/d/18MPkScBhEbJBzhzkLt-q-ZyWwq9eka3_/view?usp=share_link"
cart_bins = "https://drive.google.com/file/d/1Fymi1njrhJISFhGKIgB1hNmMknp_x-yI/view?usp=share_link"
cart_total_counts = "https://drive.google.com/file/d/1ifIrlhnkTR_ELnwQspahxydURaGBOfxc/view?usp=share_link"
cart_reordered_counts = "https://drive.google.com/file/d/1pbGRTjbkwct_P_CcSvQ412vB9ArWunBR/view?usp=share_link"
frequency_ratings = "https://drive.google.com/file/d/1wJESa73l9bvpNvd2tOWIQYd0XizWLcNZ/view?usp=share_link"
days_ratings = "https://drive.google.com/file/d/1g2SCF7waIj5xuwCYoUV9iOf6PV5muD58/view?usp=share_link"
cart_ratings = "https://drive.google.com/file/d/1jZG3cLPOjKi6Coc3GgO4VBeukoCwgbO0/view?usp=share_link"
total_ratings = "https://drive.google.com/file/d/1Sng4F4aMM3q9r_LVSZOr5KlsC8pMYtEh/view?usp=share_link"
frequency_map_10 = "https://drive.google.com/file/d/1wXs48DEq862wbSLBfqFU935cxIcHHuu-/view?usp=share_link"
